# Generated by Django 3.2.12 on 2022-03-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_deviceproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceproperty',
            name='df',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='deviceproperty',
            name='name',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
