version: "3.7"

services:
  webthingstalk:
    build:
      context: .
    image: webthingstalk:${USER}
    restart: on-failure
    ports:
      - 8000:8000
    volumes:
      - ./conf/env/env:/app/conf/env/env:ro
      - ./conf/gunicorn/gunicorn.config.py:/app/conf/gunicorn/gunicorn.config.py
      - webthingstalk-static-data:/app/webthingstalk/static/
    networks:
      - webthingstalk-net
    depends_on:
      - db
    environment:
      - DEPLOYMENT=True
      - PIPENV_PIPFILE=/app/Pipfile
    command: >
      pipenv run gunicorn -c conf/gunicorn/gunicorn.config.py core.wsgi

  nginx:
    image: nginx:1.15.11-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx/nginxconfig.io:/etc/nginx/nginxconfig.io
      - ./conf/nginx/sites-available:/etc/nginx/sites-available
      - ./conf/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/ssl:/etc/nginx/ssl
      - ./webthingstalk/static:/static
    networks:
      - webthingstalk-net

  db:
    image: mysql:8.0.27
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    command: >
      --sql_mode='' --innodb_strict_mode=OFF --character-set-server=utf8mb4 --wait-timeout=31536000 --interactive-timeout=31536000
    environment:
      MYSQL_ROOT_PASSWORD: root-password # please change it
      MYSQL_USER: webthingstalk
      MYSQL_PASSWORD: webthingstalk-password # please change it
    networks:
      - webthingstalk-net

  webthings-gateway:
    image: webthingsio/gateway:latest
    restart: always
    volumes:
      - default-gateway-data:/home/node/.webthings
    ports:
      - 8080:8080
      - 4443:4443
    networks:
      - webthingstalk-net
    environment:
      TZ: Asia/Taipei

volumes:
  default-gateway-data:
  db-data:
  webthingstalk-static-data:


networks:
  webthingstalk-net:
    driver: bridge
