# Generated by Django 3.2.12 on 2022-03-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20220307_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceproperty',
            old_name='df',
            new_name='idf',
        ),
        migrations.AddField(
            model_name='deviceproperty',
            name='odf',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
