# Generated by Django 3.2.12 on 2022-03-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_deviceproperty_odf'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='href',
            field=models.TextField(null=True),
        ),
    ]
