# Generated by Django 3.2.12 on 2022-04-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_deviceurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceurl',
            old_name='creat_time',
            new_name='create_time',
        ),
    ]
