# Generated by Django 3.2.12 on 2022-04-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_rename_creat_time_deviceurl_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='type',
            new_name='device_base',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='claim',
            new_name='device_model',
        ),
        migrations.RemoveField(
            model_name='device',
            name='model',
        ),
    ]
