# Generated by Django 3.2.12 on 2022-04-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_auto_20220407_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='name',
            new_name='device_name',
        ),
    ]
