# Generated by Django 3.2.12 on 2022-04-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_rename_name_device_device_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='href',
        ),
    ]
