'''
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
'''

from pathlib import Path
import sys
from django.contrib.messages import constants as messages


MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

sys.modules['fontawesome_free'] = __import__('fontawesome-free')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-juvbooq=my2)1@*c4-1tkheklo@qoaw#i!e$=8+lj(27g0g&yv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'devices.apps.DevicesConfig',
    'xtalk_template',
    'fontawesome_free',
    'sslserver',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'webthingstalk',
        'USER': 'postgres',
        'PASSWORD': 'asdf1234',
        'HOST': '192.168.52.140',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django X Talk Template
AUTH_USER_MODEL = 'devices.User'
XTALK_REFRESHTOKEN_MODEL = 'devices.RefreshToken'
XTALK_ACCESSTOKEN_MODEL = 'devices.AccessToken'

XTALK_OAUTH2_CLIENT_ID = 'MB5Qzv4qxH4engGU2xJUZq2jpz4OCae59H8dXV3m'
XTALK_OAUTH2_CLIENT_SECRET = 'uQUjC3yQNNRHlLiDkTiQcylhGB0eTquMcf3ylPVi9XvlGZwZEUSG1G2WphewtEavXzGkVWRi0BHu3bnhZH5P9XUVQnAmS2vPFFVqqzpox0bRxvGmt8S1POi1zkRpZSs9Ype5gIx6Ri3uCOJ2ESJ89HGZXRPeixxO'
XTALK_OAUTH2_REDIRECT_URI = 'https://127.0.0.1:8000/auth/callback'
XTALK_OIDC_DISCOVERY_ENDPOINT = 'https://account-test.iottalk2.tw/.well-known/openid-configuration'
XTALK_OAUTH2_REVOCATION_ENDPOINT = 'https://account-test.iottalk2.tw/oauth2/v1/revoke/'

# Default WebThings Gateway
DEFAULT_GATEWAY_URL = 'http://192.168.52.140:8080'
DEFAULT_GATEWAY_USERNAME = 'iottalk@iottalk.tw'
DEFAULT_GATEWAY_PASSWORD = 'iottalk'
